version: '2'
services:
    cool-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/cool/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=cool
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
